Added a Pre-Loading Screen
zero-to-mastery/WebBlocks pull request #101
Opened 2021-10-26 02:30 UTC by yashraj2003e

Issue #105

2021-10-27 17:52 UTC, r4pt0s commented
@yashraj2003e
Please resolve all merge conflicts and make sure you are targeting the dev branch of this repo in your PR.

Also, create a issue about what you want like to implement with a basic description and why we need it.
Make sure you link the issue to your PR then

2021-10-28 17:14 UTC, yashraj2003e commented
> @yashraj2003e
> Please resolve all merge conflicts and make sure you are targeting the dev branch of this repo in your PR.
> 
> Also, create a issue about what you want like to implement with a basic description and why we need it.
> Make sure you link the issue to your PR then

Hello sir, thank you for your kindness towards me. I had a doubt that how can i target the dev branch i tried but couldn't figure it, should i create a new pull request ? Thank You.

2021-10-28 18:37 UTC, r4pt0s commented
> > @yashraj2003e
> > Please resolve all merge conflicts and make sure you are targeting the dev branch of this repo in your PR.
> > Also, create a issue about what you want like to implement with a basic description and why we need it.
> > Make sure you link the issue to your PR then
> 
> Hello sir, thank you for your kindness towards me. I had a doubt that how can i target the dev branch i tried but couldn't figure it, should i create a new pull request ? Thank You.

I already changed it to target the dev branch.
If you make another PR, make sure that you choose the dev branch of this repo and not the main branch. You can select it while you create the PR.
@yashraj2003e

2021-10-28 18:40 UTC, yashraj2003e commented
> > > @yashraj2003e
> > > Please resolve all merge conflicts and make sure you are targeting the dev branch of this repo in your PR.
> > > Also, create a issue about what you want like to implement with a basic description and why we need it.
> > > Make sure you link the issue to your PR then
> > 
> > Hello sir, thank you for your kindness towards me. I had a doubt that how can i target the dev branch i tried but couldn't figure it, should i create a new pull request ? Thank You.
> 
> I already changed it to target the dev branch.
> If you make another PR, make sure that you choose the dev branch of this repo and not the main branch. You can select it while you create the PR.
> @yashraj2003e 

Thank You sir 😊.

2021-10-28 18:45 UTC, r4pt0s requested changes
A few changes are necessary @yashraj2003e

2021-10-28 18:45 UTC, r4pt0s commented on src/components/hamburger-menu/hamburger-menu.tsx
> +          <img src="../assets/img/logo_transparent.png" alt="Logo" width="150" height="100" />
Why did you change the path here?
It is already working as far as I saw it in the last build

2021-10-28 18:45 UTC, r4pt0s commented on src/index.html
> +    <link rel="stylesheet" href="style.css" />
Why did you change the path here?
This will break the styling.
Please add your css to this file
https://github.com/zero-to-mastery/WebBlocks/blob/main/src/global/global.scss

2021-10-28 18:45 UTC, r4pt0s commented on src/index.html
> +    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
Please remove jquery here and use native Javascript methods for selecting elements like document.querySelector

2021-10-28 18:45 UTC, r4pt0s commented on src/style.css
> +.loader_bg{
Please add your styles to this file
https://github.com/zero-to-mastery/WebBlocks/blob/main/src/global/global.scss

2021-10-29 18:26 UTC, r4pt0s commented
@yashraj2003e
There are still two things missing.

- delete the jquery script from index.html
- fix the asset import path. 

You can see both things in my review as not resolved

Also, why did you delete the package.lock.json file?

2021-10-30 08:19 UTC, closed without merging