Added Toast Notification Component.
zero-to-mastery/WebBlocks pull request #87
Opened 2021-10-21 16:39 UTC by Chetan-khachane

@r4pt0s  ,Resolved #84

2021-10-21 18:19 UTC, r4pt0s requested changes
Please consider adding the requested changes from my review @Chetan-khachane

2021-10-21 18:19 UTC, r4pt0s commented on src/components/toast-notify/toast-notify.tsx
> +  @Prop() message: string;
@Chetan-khachane you could use slots instead of props for the message.
Would be cleaner and easier to use.

2021-10-21 18:19 UTC, r4pt0s commented on src/components/toast-notify/toast-notify.tsx
> +    const icons = {
@Chetan-khachane please extract the icons into a own file because the source code is a bit noisy with all of this html code 😅

2021-10-21 18:19 UTC, r4pt0s commented on src/components/toast-notify/toast-notify.tsx
> +            </svg>
Same here @Chetan-khachane
Please but the svg code in its own file or together with the other ones in one file.

2021-10-22 03:10 UTC, Chetan-khachane commented on src/components/toast-notify/toast-notify.tsx
> +  @Prop() message: string;
added slot for message.

2021-10-22 03:12 UTC, Chetan-khachane commented
@r4pt0s , Done changes according to request. Thanks for notifying me.

2021-10-22 06:15 UTC, merged